language: python
python:
  - 2.6
  - 2.7
env:
  - REQUIREMENTS=development SETTINGS=facebook_example.settings TESTS=feedly DJANGO=1.3.1
  - REQUIREMENTS=development SETTINGS=facebook_example.settings TESTS=feedly DJANGO=1.4
postgres:
  adapter: sqlite3
  database: feedly_test
install:
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - python setup.py install
  - pip install -q Django==$DJANGO --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 feedly"
  - pyflakes -x W src
script:
  - python setup.py test